spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rental?useSSL=false
    username: root
    password: Banned@123
  jpa:
    hibernate.ddl-auto: validate
    generate-ddl: true
    show-sql: true
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect